name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy from existing project directory
      run: |
        cd /home/lawly-prod/ai-service
        git fetch --all
        git reset --hard origin/main
        docker compose up -d --build
